### ISSUE TITLE
Some Clarification on Certain Words and Expressions

### ISSUE THREAD

**Issue by copperisland** [mufasaYC/tasks-localization#14]
I have a few questions about the context of certain words and phrases.

So here's my "list":

__**- Line 112:  "We have nothing on you"**__

_Does this mean we have no personal information stored or something else?_

__**- Line 250: "Support for %@ will be available soon!"**__

_What does %@ represent? Is it a device? I'm asking to see whether I need to include an article before the object._

__**- Line 253: "Popular"**__

_What does popular refer to? eg popular subscription choice, popular feature etc._ 

If I have a bit more context I can check back to see if the translation makes grammatical sense. Thanks! 😺

**Comment by mufasaYC** [comment]
- We have nothing on you stands for no data collection on the user
- %@ here is a placeholder for a feature, example "sharing"
- Popular would stand for popular subscription choice 

i hope these answer your questions

**Comment by copperisland** [comment]
Thanks this was helpful! 

Should I close this issue or should I leave it open in case other people have questions and need clarification for translating things into their own languages?

**Comment by mufasaYC** [comment]
You can mark this issue as closed, thank you for your help! 😃
