### ISSUE TITLE
Localizing error (German)

### ISSUE THREAD

**Issue by Luca1719** [mufasaYC/tasks-localization#18]
In the German Version of Task some strings aren’t localized. Also, the Field names and status names are default in English, which should be locaized too, to be more convenient for German speaking users. 
![F901B099-E542-4660-8F93-38BFD7143150](https://user-images.githubusercontent.com/66329245/84746947-ef2f8900-afb6-11ea-841e-b2e23317f2cf.png)
![0E5C6709-0A9A-43AF-971E-568D0190C4E5](https://user-images.githubusercontent.com/66329245/84746960-f35ba680-afb6-11ea-9596-7ae1f03e005c.png)

**Comment by mufasaYC** [comment]
Thank you for pointing these out, I’ll release an update fixing these issues within a day or two! @Luca1719

**Comment by mufasaYC** [comment]
@Luca1719 this is fixed, if you could ping me on twitter, that would be awesome, https://twitter.com/mufasayc
