### ISSUE TITLE
Service or application for convenient translation

### ISSUE THREAD

**Issue by KovalevArtem** [mufasaYC/tasks-localization#2]
What are the variation for convenient translation of such projects where only lines are available?

**Comment by KovalevArtem** [comment]
For example, not so long ago I learned about such a tool: 
https://localizer.dev

**Comment by KovalevArtem** [comment]
@comradekingu Tell me, what tools can be used for localization?

**Comment by mufasaYC** [comment]
Tools are good to have, however GitHub in my opinion works really well as it's easier to keep track of everyone's contribution and I can reward them accordingly. It's also easier to modify, maintain, edit, raise issues, dispute and correct one another.

**Comment by KovalevArtem** [comment]
@mufasaYC Using services like Weblate makes life easier for translators and developers. But, as I understand it, the use of this service will cost you money (for open source projects, use is completely free) - so I did not dare to offer it to you ...

That is why I created this issues. Perhaps other translators will share their knowledge and experience! Please do not close this issues so quickly ...

**Comment by comradekingu** [comment]
I am not interested in unfree software. I would help if this was released under a libre license.

**Comment by KovalevArtem** [comment]
@comradekingu Your position is clear. But tell me what tools exist for convenient line feeds in their current form...

**Comment by comradekingu** [comment]
Every tool there is. Weblate being my preference. Would be preferable if money wasn't spent on services that similarly deprive users of freedom. Fortunately those services aren't good.
